@startuml

package Model <<Rectangle>> {
    entity VehiculeDto {
      - int @id
      - int crewMember
      - int facilityRefID
      - float fuel
      - double lat
      - double lon
      - float liquidQuantity
      - liquidType liquidType
      - typeVehicule type

        @VehiculeDto(String)
      @setter()
      @getter()
    }

    entity FireDto {
        - @id
    }
    entity FacilityDto {
        - @id
    }

    enum liquidType {
        ALL
        CARBON_DIOXIDE
        ...
    }

    package ModelVehicule <<rectangle>> {
        interface InterfaceVehicule {
            - mission
            - Vehicule info
            deplacement()
            ravitaillement()
            gestionCrew()
            findCaserne()
        }

        abstract AbstractVehicule {
            - mission
            - Vehicule info
            deplacement()
            ravitaillement()
            gestionCrew()
            findCaserne()
        }

        class Vehicule {
            - mission
            - VehiculeDto vehiculeDto
            calculScore()
        }

        InterfaceVehicule o.. AbstractVehicule
        AbstractVehicule o-- Vehicule
    }

    package Manager <<Folder>> {

        class RemoteControl {
            newMission()
        }

        package BlocAffectation <<rectangle>> {
            class Strategy {
                - feux
                - casernes
                - vehicules
                calculScore()
            }
        }

        package BlocMission <<rectangle>> {
            class Mission {
            }
        }

        class Path {
            + Path(Coord dep, Coord arr)
        }

        RemoteControl -> BlocAffectation
        Strategy -> BlocMission

    }

    package Communicator <<Folder>> {

        class Requester {

        }

        enum ConstantURL {

        }

    }

}

package Controller <<Rectangle>> {

    class VehiculeRepository {
        CRUD Vehicule
    }

    class VehiculeService {
        listVehicule()
        update()
    }

    class VehiculeRest {
        GET getListVehicule()
        POST updateVehicule()
    }

    VehiculeRest -|> VehiculeService
    VehiculeService -|> VehiculeRepository

    VehiculeService o- InterfaceVehicule

}



@enduml