@startuml

package Model <<Rectangle>> {
    entity Vehicule {
      - int @id
      - int crewMember
      - int facilityRefID
      - float fuel
      - double lat
      - double lon
      - float liquidQuantity
      - liquidType liquidType
      - typeVehicule type

      @setter()
      @getter()
    }

    entity Feu {
        - @id
    }
    entity Caserne {
        - @id
    }

    enum liquidType {
        ALL
        CARBON_DIOXIDE
        ...
    }

    package Manager <<Folder>> {

        class RemoteCall {
            requestFires()
            requestVehicules()
            casernes()
            compare()
        }

        package Affectation <<rectangle>> {
            class Strategy {
                - feux
                - casernes
                - vehicules
                calculScore()
            }
        }

        package Mission <<rectangle>> {
            class Deplacement {
                Chemin()
                DeplacementV()
                ActualisationAPI()
            }
            class EteindreFeu {
                AllerFeu()
            }
            class GestionFin {
                RentrerCaserne()
            }
        }

        RemoteCall -> Affectation
        Strategy -> Mission

        interface InterfaceVehicule {
            - mission
            - Vehicule info
            deplacement()
            ravitaillement()
            gestionCrew()
        }

        abstract AbstractVehicule {
            - mission
            - Vehicule info
            deplacement()
            ravitaillement()
            gestionCrew()
        }

        class Car {
            - mission
            - Vehicule info
        }
        class Truck {
            - mission
            - Vehicule info
        }

        InterfaceVehicule o.. AbstractVehicule
        AbstractVehicule o-- Car
        AbstractVehicule o-- Truck
    }

}

package Controller <<Rectangle>> {

    class VehiculeRepository {
        CRUD Vehicule
    }

    class VehiculeService {
        listVehicule()
        update()
    }

    class VehiculeRest {
        GET getListVehicule()
        POST updateVehicule()
    }

    VehiculeRest -|> VehiculeService
    VehiculeService -|> VehiculeRepository

    VehiculeRepository o- Vehicule
    VehiculeService o- InterfaceVehicule

}



@enduml